// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtrrqdrgxpmkezhmxwvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cnJxZHJneHBta2V6aG14d3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTMwMjQsImV4cCI6MjA1OTA4OTAyNH0.zkOAEYbZdsp5pSznO_EQ1-BSjlSeRKrPocJoQ9n8qJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);